version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: some_secret_key
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]